version: "3.9"
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: "github-releases-bot"
      POSTGRES_USER: "github-bot"
      POSTGRES_PASSWORD: "123qwe123qwe"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U github-bot -d github-releases-bot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - github-bot

  app:
    image: s3kkt/github-releases-bot
    build:
      context: .
    volumes:
      - ./configs:/etc/github-bot
    depends_on:
      - database
    command: -config="/etc/github-bot/config.yml"
    tty: true
    networks:
      - github-bot

networks:
  github-bot:
    driver: bridge
